### ISSUE TITLE
feat(nibijs): Tx hash fns and better method for querying by tx hash 

### ISSUE THREAD

**Issue by Unique-Divine** [NibiruChain/ts-sdk#258]
Context: The UX when handling the cryptographic hashes for transactions is not great in existing Cosmos tooling. Let's fix that in NibiJS. 

## Tasks
- [ ] `getTxByHash(txHashHex: string)` - Should be clearly hexadecimal
- [ ] `getByTxHashSha(txHashShe: Uint8Array)` - Bytes for a sha256 
- [ ] `txHashShaToHex` with type `(sha: Uint8Array) => string`
- [ ] `txHashHexToSha` with type `(hex: string) => Result<Uint8Array>` | `Result` meaning handle the error as a value
