### ISSUE TITLE
feat(nibijs): ibc queries

### ISSUE THREAD

**Issue by Unique-Divine** [NibiruChain/ts-sdk#65]
# Objective 

Add `ibc` and `ibc-transfer` queries to `nibijs`.

## Background

The `nibid` CLI exposes queries under the `ibc` subcommand. 

### nibid query ibc

Output:
```
Querying commands for the IBC module

Usage:
  nibid query ibc [flags]
  nibid query ibc [command]

Available Commands:
  channel     IBC channel query subcommands
  client      IBC client query subcommands
  connection  IBC connection query subcommands
```

### nibid query ibc-transfer

Output:
```
IBC fungible token transfer query subcommands

Usage:
  nibid query ibc-transfer [command]

Available Commands:
  denom-hash     Query the denom hash info from a given denom trace
  denom-trace    Query the denom trace info from a given trace hash or ibc denom
  denom-traces   Query the trace info for all token denominations
  escrow-address Get the escrow address for a channel
  params         Query the current ibc-transfer parameters
```

## IBC Query Extension from CosmJS

There's an implementation in CosmJS [comsjs/.../modules/ibc](https://github.com/cosmos/cosmjs/tree/33271bc51cdc865cadb647a1b7ab55d873637f39/packages/stargate/src/modules/ibc) both for queries and transactions related to IBC.

Let's add IBC queries, except using the proto types from our protojs package. This way, if Nibiru has an IBC dependency that conflicts with the version used in CosmJS, we won't encounter errors. 

## Task List 
 
IBC channel queries
- [ ] feat: implement queries
- [ ] test: add tests

IBC client queries 
- [ ] feat: implement queries
- [ ] test: add tests

IBC client queries
- [ ] feat: implement queries
- [ ] test: add tests

IBC connection queries 
- [ ] feat: implement queries
- [ ] test: add tests

IBC transfer queries
- [ ] feat: implement queries
- [ ] test: add tests

IBC verified queries
- [ ] feat: implement queries
- [ ] test: add tests
