### ISSUE TITLE
docs,epic(indexer-nibi): Add usage examples for all queries

### ISSUE THREAD

**Issue by Unique-Divine** [NibiruChain/ts-sdk#92]
## Queries to Create Examples For

- [ ] Link to Examples in this ticket: ___
- [ ] Document an example with a WHERE clause
- [ ] Document an IBC example and explain the response

## Child Tickets [From 2023]
- [x] feat(indexer-nibi): query `balances`
- [x] #97
- [x] #98
- [x] #91
- [x] #96
- [x] #121
- [x] feat(indexer-nibi): query `positionChanges`
- [x] feat(indexer-nibi): query `positions`
- [x] feat(indexer-nibi): query `statsVolume`
- [x] #95
- [x] #93
- [x] #94
- [x] feat(indexer-nibi): query `unbondings`
- [x] feat(indexer-nibi): query `validators`
- [x] feat(indexer-nibi): query `vpoolConfigs`

**Comment by cgilbe27** [comment]
Reopening as I still think having something like this is useful

**Comment by Unique-Divine** [comment]
Maybe a good way to handle this is to aim first for documenting examples of patterns that are common across many queries. For example, we could show a few examples on:
- [ ] Queries with unintuitive WHERE clauses
- [ ] Queries related to IBC
- [ ] Queries that we expect to be most common, such as balance queries and tx history
